#!/usr/bin/env python3
"""Rebuild .claude/devlog/index.json and tldr.md from entries/**/*.md.

Source of truth: markdown files in entries/. This script never writes to entries.
Generates two derived artifacts:
  - index.json — machine-readable (jq-friendly), with _schema header + preview
  - tldr.md    — human/LLM-friendly digest, newest first

Run after adding a new entry, or as a pre-commit hook.

Usage: python3 .claude/devlog/rebuild-index.py
Exit: 0 ok / 1 schema/duplicate-id error.
"""
from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

DEVLOG_ROOT = Path(__file__).parent
ENTRIES_DIR = DEVLOG_ROOT / "entries"
INDEX_PATH = DEVLOG_ROOT / "index.json"
TLDR_PATH = DEVLOG_ROOT / "tldr.md"

REQUIRED_FIELDS = ("id", "date", "title")
OPTIONAL_FIELDS = ("tags", "status", "supersedes")
PREVIEW_MAX_LEN = 280
# Word-boundary cut at <70% of max would chop the preview too aggressively;
# in that case keep the char-level cut and lose a partial word at the end.
PREVIEW_WORD_BOUNDARY_MIN_RATIO = 0.7

SCHEMA = {
    "version": 1,
    "source_of_truth": "entries/*.md frontmatter; index.json + tldr.md are regenerated by rebuild-index.py",
    "fields": {
        "id": "int, unique, monotonic; matches NNNN in filename",
        "date": "ISO YYYY-MM-DD",
        "title": "string, <80 chars, past-tense imperative",
        "tags": "list[str]; type (feature/bugfix/refactor/config/docs/security/test/cleanup/adr) + area",
        "status": "complete | superseded | wip (default: complete)",
        "supersedes": "int|null, id of replaced entry",
        "path": "relative path from .claude/devlog/",
        "preview": "1-paragraph summary, derived from first paragraph of '## Контекст' section (≤280 chars)",
    },
}


def parse_frontmatter(text: str) -> dict | None:
    """Minimal YAML-frontmatter parser. Supports str, int, and inline list [a, b]."""
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return None
    out: dict = {}
    for line in m.group(1).splitlines():
        line = line.rstrip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        if val.startswith("[") and val.endswith("]"):
            out[key] = [x.strip().strip('"\'') for x in val[1:-1].split(",") if x.strip()]
        elif val.isdigit():
            out[key] = int(val)
        else:
            out[key] = val.strip('"\'')
    return out


# Кириллица → латиница: без этого чисто русский title даёт пустой slug
_TRANSLIT = {
    "а": "a", "б": "b", "в": "v", "г": "g", "д": "d", "е": "e", "ё": "e",
    "ж": "zh", "з": "z", "и": "i", "й": "y", "к": "k", "л": "l", "м": "m",
    "н": "n", "о": "o", "п": "p", "р": "r", "с": "s", "т": "t", "у": "u",
    "ф": "f", "х": "kh", "ц": "ts", "ч": "ch", "ш": "sh", "щ": "shch",
    "ъ": "", "ы": "y", "ь": "", "э": "e", "ю": "yu", "я": "ya",
}
_TRANSLIT_TABLE = str.maketrans(_TRANSLIT)


def slugify(s: str, max_len: int = 60) -> str:
    s = s.lower().translate(_TRANSLIT_TABLE)
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s[:max_len].rstrip("-")


def slugify_legacy(s: str, max_len: int = 60) -> str:
    """Поведение до транслитерации — имена существующих entry-файлов
    создавались им; валидация принимает оба, переименование не требуется."""
    s = s.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s[:max_len].rstrip("-")


def extract_preview(text: str) -> str:
    """First paragraph of '## Контекст' section (fallback: first body paragraph).

    Strips frontmatter, markdown emphasis, joins folded lines into one paragraph,
    truncates to PREVIEW_MAX_LEN at word boundary.
    """
    # Strip frontmatter
    m = re.match(r"^---\n.*?\n---\n", text, re.DOTALL)
    body = text[m.end():] if m else text

    # Try to locate '## Контекст' (case-sensitive — our convention)
    section_match = re.search(r"^##\s+Контекст\s*$", body, re.MULTILINE)
    if section_match:
        section = body[section_match.end():]
    else:
        # Fallback: drop leading H1 if present
        h1 = re.match(r"^\s*#\s+.*?\n", body)
        section = body[h1.end():] if h1 else body

    # Find first non-empty paragraph (bounded by blank line or next heading)
    paragraph: list[str] = []
    for raw_line in section.splitlines():
        stripped = raw_line.strip()
        if not stripped:
            if paragraph:
                break
            continue
        if stripped.startswith("#"):
            if paragraph:
                break
            continue
        paragraph.append(stripped)

    if not paragraph:
        return ""

    out = " ".join(paragraph)
    # Strip markdown emphasis but keep content
    out = re.sub(r"\*\*(.+?)\*\*", r"\1", out)
    out = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)", r"\1", out)
    out = re.sub(r"`([^`]+)`", r"\1", out)

    if len(out) > PREVIEW_MAX_LEN:
        cut = out[:PREVIEW_MAX_LEN]
        last_space = cut.rfind(" ")
        if last_space > int(PREVIEW_MAX_LEN * PREVIEW_WORD_BOUNDARY_MIN_RATIO):
            cut = cut[:last_space]
        out = cut.rstrip(",.;:- ") + "…"
    return out


def collect_entries() -> tuple[list[dict], list[str]]:
    entries: list[dict] = []
    errors: list[str] = []
    if not ENTRIES_DIR.exists():
        return entries, [f"missing dir: {ENTRIES_DIR}"]

    for md_path in sorted(ENTRIES_DIR.rglob("*.md")):
        rel = md_path.relative_to(DEVLOG_ROOT)
        try:
            text = md_path.read_text(encoding="utf-8")
        except OSError as e:
            errors.append(f"{rel}: read failed ({e})")
            continue
        fm = parse_frontmatter(text)
        if fm is None:
            errors.append(f"{rel}: missing or malformed frontmatter")
            continue
        for field in REQUIRED_FIELDS:
            if field not in fm:
                errors.append(f"{rel}: required field '{field}' missing")
                break
        else:
            expected_slug = slugify(str(fm["title"]))
            stem = md_path.stem
            m = re.match(r"^(\d{1,6})-(.+)$", stem)
            if not m:
                errors.append(f"{rel}: filename must match NNNN-slug pattern")
                continue
            file_id = int(m.group(1))
            file_slug = m.group(2)
            if fm["id"] != file_id:
                errors.append(f"{rel}: frontmatter id {fm['id']} != filename id {file_id}")
                continue
            if file_slug not in (expected_slug, slugify_legacy(str(fm["title"]))):
                errors.append(f"{rel}: filename slug '{file_slug}' != slugify(title)='{expected_slug}'")
                continue
            entries.append({
                "id": file_id,
                "date": fm["date"],
                "title": fm["title"],
                "tags": fm.get("tags", []),
                "status": fm.get("status", "complete"),
                "supersedes": fm.get("supersedes"),
                "path": str(rel).replace("\\", "/"),
                "preview": extract_preview(text),
            })

    seen: dict[int, str] = {}
    for e in entries:
        if e["id"] in seen:
            errors.append(f"duplicate id {e['id']}: {seen[e['id']]} vs {e['path']}")
        else:
            seen[e["id"]] = e["path"]

    entries.sort(key=lambda e: e["id"])
    return entries, errors


def write_tldr(entries: list[dict]) -> None:
    """Render newest-first digest of entries with preview + link."""
    lines: list[str] = [
        "# Devlog TL;DR",
        "",
        "Derived view — генерируется `rebuild-index.py` из `entries/*.md`.",
        "Источник правды — `entries/`. **Этот файл не редактируется вручную.**",
        "",
        "Назначение: холодный вход агента / читателя в проектную хронологию",
        "без открытия всех entry-файлов целиком. Записи отсортированы по id desc.",
        "",
    ]
    for e in sorted(entries, key=lambda x: x["id"], reverse=True):
        marker = ""
        if e["status"] == "superseded":
            marker = " · _superseded_"
        elif e["status"] == "wip":
            marker = " · _wip_"
        elif e.get("supersedes"):
            marker = f" · _supersedes #{e['supersedes']}_"

        tags = ", ".join(e.get("tags") or [])
        lines.append("---")
        lines.append("")
        lines.append(f"## #{e['id']} · {e['date']} · {e['title']}{marker}")
        lines.append("")
        if tags:
            lines.append(f"**Tags:** {tags}")
            lines.append("")
        if e.get("preview"):
            lines.append(e["preview"])
            lines.append("")
        lines.append(f"[→ {e['path']}]({e['path']})")
        lines.append("")

    TLDR_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    entries, errors = collect_entries()
    if errors:
        print("ERRORS:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    index = {
        "_schema": SCHEMA,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "entry_count": len(entries),
        "entries": entries,
    }
    INDEX_PATH.write_text(json.dumps(index, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    write_tldr(entries)
    print(f"index.json + tldr.md updated: {len(entries)} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
