#!/usr/bin/env python3
"""Auto-generate REVIEW.md index of pending proposals awaiting human review.

Reads:
  - .claude/loop/proposals/iter-NNNN-<basename>.diff  (proposal payload)
  - .claude/loop/journal.md                           (cross-ref H-XXX + STATUS)

Writes (default: .claude/loop/proposals/REVIEW.md; --stdout: stdout):
  Markdown index grouped by status. For each pending proposal:
    iter, H-XXX (if known), target (basename), diff stats (+added/-removed),
    relative diff path, linked journal line.

Exit codes:
  0 — read-only success (default mode); also when --check finds zero pending
  1 — --check + ≥1 pending proposal (CI gating signal)
  2 — usage error / IO error

Usage:
  proposals-review.py                       # write REVIEW.md, print summary
  proposals-review.py --stdout              # print REVIEW.md content to stdout
  proposals-review.py --check               # exit 1 if any pending
  proposals-review.py --proposals-dir DIR   # override scan dir
"""

from __future__ import annotations
import argparse
import datetime as _dt
import re
import sys
from pathlib import Path


PROPOSAL_RE = re.compile(r"^iter-(\d{4})-(.+)\.diff$")
# journal line example:
#   2026-05-11 03:30:00Z iter-0011 PROPOSAL H-018 .claude/loop/run.sh
JOURNAL_PROPOSAL_RE = re.compile(
    r"^(\S+\s+\S+)\s+iter-(\d{4})\s+PROPOSAL\s+(H-\d+)\s+(.+?)\s*$"
)


def parse_proposal_filename(name: str) -> tuple[int, str] | None:
    m = PROPOSAL_RE.match(name)
    if not m:
        return None
    return int(m.group(1)), m.group(2)


def diff_stats(path: Path) -> tuple[int, int]:
    """Count +/- lines in a unified diff. Skips ++/-- file headers."""
    added = removed = 0
    try:
        for line in path.read_text(errors="replace").splitlines():
            if line.startswith("+++") or line.startswith("---"):
                continue
            if line.startswith("+"):
                added += 1
            elif line.startswith("-"):
                removed += 1
    except OSError:
        pass
    return added, removed


def collect_proposals(proposals_dir: Path) -> list[dict]:
    """Returns list of {iter, basename, path, added, removed} sorted by iter desc."""
    out: list[dict] = []
    if not proposals_dir.is_dir():
        return out
    for p in proposals_dir.iterdir():
        parsed = parse_proposal_filename(p.name)
        if not parsed:
            continue
        iter_n, basename = parsed
        added, removed = diff_stats(p)
        out.append({
            "iter": iter_n,
            "basename": basename,
            "path": p,
            "added": added,
            "removed": removed,
        })
    return sorted(out, key=lambda x: x["iter"], reverse=True)


def collect_journal_proposals(journal_path: Path) -> dict[int, dict]:
    """Returns {iter_n: {timestamp, hyp, target}} parsed from PROPOSAL lines."""
    out: dict[int, dict] = {}
    if not journal_path.exists():
        return out
    for line in journal_path.read_text(errors="replace").splitlines():
        m = JOURNAL_PROPOSAL_RE.match(line)
        if not m:
            continue
        out[int(m.group(2))] = {
            "timestamp": m.group(1),
            "hyp": m.group(3),
            "target": m.group(4),
        }
    return out


def render_review(proposals: list[dict], journal: dict[int, dict]) -> str:
    """Build REVIEW.md content."""
    today = _dt.date.today().isoformat()
    lines: list[str] = []
    lines.append("# Proposals review queue")
    lines.append("")
    lines.append(f"Auto-generated by `python3 .claude/loop/proposals-review.py`. "
                 f"Do not edit by hand — regenerated each invocation.")
    lines.append("")
    lines.append(f"**Pending**: {len(proposals)} | **Last regen**: {today}")
    lines.append("")

    if not proposals:
        lines.append("## Pending (0)")
        lines.append("")
        lines.append("_No proposals awaiting review._")
        lines.append("")
        return "\n".join(lines) + "\n"

    lines.append(f"## Pending ({len(proposals)})")
    lines.append("")
    for pr in proposals:
        meta = journal.get(pr["iter"])
        hyp = meta["hyp"] if meta else "H-???"
        target = meta["target"] if meta else pr["basename"]
        lines.append(f"### iter-{pr['iter']:04d} — {hyp} `{target}`")
        lines.append("")
        lines.append(f"- diff: +{pr['added']}/-{pr['removed']}")
        lines.append(f"- file: `{pr['path']}`")
        if meta:
            lines.append(f"- journal: `{meta['timestamp']}`")
        else:
            lines.append("- journal: (no PROPOSAL line found — orphan diff)")
        lines.append("")
    lines.append("## How to apply")
    lines.append("")
    lines.append("Each diff is reviewed manually. To apply after approval:")
    lines.append("```")
    lines.append("git apply .claude/loop/proposals/iter-NNNN-<basename>.diff")
    lines.append("# verify, then commit:")
    lines.append("git commit -am 'loop: apply H-XXX proposal — <one-line>'")
    lines.append("# remove processed diff:")
    lines.append("rm .claude/loop/proposals/iter-NNNN-<basename>.diff")
    lines.append("# regenerate REVIEW.md:")
    lines.append("python3 .claude/loop/proposals-review.py")
    lines.append("```")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    p = argparse.ArgumentParser(description=(__doc__ or "").split("\n", 1)[0])
    p.add_argument("--proposals-dir", default=".claude/loop/proposals",
                   help="proposals dir to scan (default: .claude/loop/proposals)")
    p.add_argument("--journal", default=".claude/loop/journal.md",
                   help="journal path for PROPOSAL line cross-ref")
    p.add_argument("--output", default=None,
                   help="REVIEW.md output path (default: <proposals-dir>/REVIEW.md)")
    p.add_argument("--stdout", action="store_true",
                   help="emit to stdout instead of writing REVIEW.md")
    p.add_argument("--check", action="store_true",
                   help="exit 1 if any pending proposals (CI gating)")
    args = p.parse_args()

    proposals_dir = Path(args.proposals_dir)
    journal_path = Path(args.journal)
    proposals = collect_proposals(proposals_dir)
    journal = collect_journal_proposals(journal_path)
    content = render_review(proposals, journal)

    if args.stdout:
        sys.stdout.write(content)
    else:
        out_path = Path(args.output) if args.output \
            else proposals_dir / "REVIEW.md"
        try:
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(content)
        except OSError as e:
            print(f"ERROR: cannot write {out_path}: {e}", file=sys.stderr)
            return 2
        print(f"REVIEW.md regenerated: {out_path} ({len(proposals)} pending)")

    if args.check and proposals:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
